-- ============================================================
-- Migration 012: AI Finder Results and Conversations
-- ============================================================
-- Tables:
--   ai_finder_results
--   ai_finder_program_matches
--   ai_conversations
--   ai_messages
--   ai_usage_logs
--
-- Depends on:
--   001_custom_types  — update_updated_at_column(), session_type values
--   002_auth_roles    — has_role(), has_permission(), user_profiles
--   006_programs      — programs
--   011_student_profiles — student_profiles
--
-- Purpose:
--   ai_finder_results and ai_finder_program_matches store the output
--   of the Best-Fit Finder: a structured recommendation shortlist
--   derived from real database records, explained by an LLM.
--
--   ai_conversations and ai_messages store chat sessions and their
--   messages. Chat is separate from Finder results.
--
--   ai_usage_logs is a cost/token audit log written exclusively by
--   server endpoints using the service role.
--
-- Core AI rule:
--   The LLM must not invent program recommendations.
--   ai_finder_program_matches must reference only real programs
--   from the live programs table. The server selects programs
--   via database filters before calling the LLM.
--
-- Anonymous session handling:
--   Anonymous finder results and conversations are NOT accessible
--   through browser RLS. All anonymous AI access goes through server
--   endpoints using the Supabase service role, which bypasses RLS.
--   Direct anon-tier RLS policies are intentionally omitted.
--
-- No pgvector, embeddings, or RAG tables in this migration.
-- No ai_finder_scholarship_matches in this migration.
--
-- RLS summary:
--   ai_finder_results:
--     Logged-in SELECT — parent profile.user_id = auth.uid()
--     Logged-in DELETE — parent profile.user_id = auth.uid()
--     No browser INSERT — result rows are created by server endpoints only, because
--       the server must run database filtering, scoring, LLM explanation, and
--       token/cost tracking before any result row is persisted.
--     No logged-in UPDATE (server updates via service role)
--     super_admin SELECT/DELETE for support/moderation
--   ai_finder_program_matches:
--     Logged-in SELECT — grandparent profile.user_id = auth.uid()
--     No browser INSERT or DELETE — program matches are generated by the server
--       scoring engine and written via service role only.
--     super_admin SELECT/DELETE
--   ai_conversations:
--     Logged-in SELECT/DELETE — user_id = auth.uid().
--     Logged-in INSERT/UPDATE WITH CHECK — user_id = auth.uid() AND (student_profile_id
--       IS NULL OR belongs to auth.uid() with is_anonymous = false). Prevents linking a
--       conversation to another user's profile or to an anonymous profile via browser.
--       Also prevents null user_id (no anonymous conversations via browser).
--     super_admin SELECT/DELETE
--   ai_messages:
--     Logged-in SELECT — parent conversation.user_id = auth.uid()
--     No browser INSERT, UPDATE, or DELETE — message writes are server-only because
--       the endpoint must validate role, call the model, track cost, and store context.
--     super_admin SELECT/DELETE
--   ai_usage_logs:
--     SELECT — view_ai_logs permission OR super_admin
--     No authenticated INSERT (service role only)
--     No UPDATE/DELETE (append-only audit log)
-- ============================================================


-- ============================================================
-- TABLE: ai_finder_results
-- ============================================================
-- Structured recommendation report produced by the Best-Fit Finder.
-- One result per Finder run. Contains the LLM explanation and
-- aggregated token usage. Actual program matches are in
-- ai_finder_program_matches.
--
-- Write access (INSERT/UPDATE) is intentionally server-only.
-- Browser clients must not be able to fabricate ai_explanation,
-- ai_model_used, token counts, or result_status. The server endpoint
-- must run database filtering, rule-based scoring, and the LLM call
-- before creating a result row — all writes use the service role.
-- Logged-in users may DELETE their own results (cleanup action only).
-- ------------------------------------------------------------
CREATE TABLE public.ai_finder_results (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  student_profile_id      uuid        NOT NULL REFERENCES public.student_profiles(id) ON DELETE CASCADE,

  result_status           text        NOT NULL DEFAULT 'pending'
    CHECK (result_status IN ('pending', 'complete', 'failed')),

  -- Number of programs in the shortlist.
  shortlist_count         integer     NOT NULL DEFAULT 0,

  -- LLM-generated explanation of the shortlist. Based only on
  -- real program records selected by server-side database filtering.
  ai_explanation          text,
  ai_model_used           text,

  prompt_token_count      integer     NOT NULL DEFAULT 0,
  completion_token_count  integer     NOT NULL DEFAULT 0,

  created_at              timestamptz NOT NULL DEFAULT now(),

  -- Set only for anonymous results; triggers cleanup cron job.
  expires_at              timestamptz
);

CREATE INDEX idx_ai_finder_results_student_profile_id ON public.ai_finder_results (student_profile_id);
CREATE INDEX idx_ai_finder_results_result_status      ON public.ai_finder_results (result_status);
CREATE INDEX idx_ai_finder_results_created_at         ON public.ai_finder_results (created_at);
CREATE INDEX idx_ai_finder_results_expires_at         ON public.ai_finder_results (expires_at);
-- Used by cleanup cron job to find expired anonymous results.
CREATE INDEX idx_ai_finder_results_expires_nonnull    ON public.ai_finder_results (expires_at)
  WHERE expires_at IS NOT NULL;

ALTER TABLE public.ai_finder_results ENABLE ROW LEVEL SECURITY;

-- Logged-in users can read their own Finder results (via parent profile ownership).
CREATE POLICY "ai_finder_results_select_own" ON public.ai_finder_results
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.student_profiles sp
      WHERE sp.id = ai_finder_results.student_profile_id
        AND sp.user_id = auth.uid()
    )
  );

-- No INSERT policy for authenticated clients.
-- All Finder result rows are created by server endpoints using the service role.
-- This ensures database filtering, scoring, LLM explanation, and cost tracking
-- all complete before any result row is persisted.

-- Logged-in users can delete their own Finder results.
CREATE POLICY "ai_finder_results_delete_own" ON public.ai_finder_results
  FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.student_profiles sp
      WHERE sp.id = ai_finder_results.student_profile_id
        AND sp.user_id = auth.uid()
    )
  );

-- super_admin can read all Finder results for support and moderation.
CREATE POLICY "ai_finder_results_select_super_admin" ON public.ai_finder_results
  FOR SELECT TO authenticated
  USING (has_role('super_admin'));

-- super_admin can delete Finder results for support and moderation.
CREATE POLICY "ai_finder_results_delete_super_admin" ON public.ai_finder_results
  FOR DELETE TO authenticated
  USING (has_role('super_admin'));


-- ============================================================
-- TABLE: ai_finder_program_matches
-- ============================================================
-- Ranked program records inside an AI Finder result.
-- Programs here must be real rows from the live programs table.
-- The LLM does not select programs — the server does via
-- database filtering and rule-based scoring before calling the LLM.
--
-- Write access (INSERT/UPDATE/DELETE) is intentionally server-only.
-- Browser clients must not be able to fabricate or remove program
-- matches, as this would undermine the integrity of the scoring
-- pipeline. All match rows are written via service role through
-- server endpoints.
-- ------------------------------------------------------------
CREATE TABLE public.ai_finder_program_matches (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  ai_finder_result_id uuid        NOT NULL REFERENCES public.ai_finder_results(id) ON DELETE CASCADE,

  -- Must reference a real published program. RESTRICT prevents silent
  -- data loss if a program is deleted while still referenced here.
  program_id          uuid        NOT NULL REFERENCES public.programs(id) ON DELETE RESTRICT,

  rank                integer     NOT NULL,
  score               numeric,

  -- Structured match explanation (e.g. fields that matched, weight values).
  match_reasons       jsonb,

  -- Any caveats or mismatches flagged by the scoring logic.
  warnings            jsonb,

  created_at          timestamptz NOT NULL DEFAULT now(),

  -- Each program appears at most once per result.
  CONSTRAINT uq_finder_result_program UNIQUE (ai_finder_result_id, program_id),
  -- Each rank position is unique within a result.
  CONSTRAINT uq_finder_result_rank    UNIQUE (ai_finder_result_id, rank)
);

CREATE INDEX idx_ai_finder_program_matches_result_id  ON public.ai_finder_program_matches (ai_finder_result_id);
CREATE INDEX idx_ai_finder_program_matches_program_id ON public.ai_finder_program_matches (program_id);
CREATE INDEX idx_ai_finder_program_matches_rank       ON public.ai_finder_program_matches (rank);
CREATE INDEX idx_ai_finder_program_matches_score      ON public.ai_finder_program_matches (score);
CREATE INDEX idx_ai_finder_program_matches_created_at ON public.ai_finder_program_matches (created_at);

ALTER TABLE public.ai_finder_program_matches ENABLE ROW LEVEL SECURITY;

-- Logged-in users can read matches inside their own Finder results.
CREATE POLICY "ai_finder_program_matches_select_own" ON public.ai_finder_program_matches
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM   public.ai_finder_results  afr
      JOIN   public.student_profiles   sp  ON sp.id = afr.student_profile_id
      WHERE  afr.id      = ai_finder_program_matches.ai_finder_result_id
        AND  sp.user_id  = auth.uid()
    )
  );

-- No INSERT policy for authenticated clients.
-- No DELETE policy for authenticated clients.
-- Program match rows are written and removed exclusively via service role
-- through server endpoints (scoring engine, Finder result cleanup).

-- super_admin can read and delete all program matches.
CREATE POLICY "ai_finder_program_matches_select_super_admin" ON public.ai_finder_program_matches
  FOR SELECT TO authenticated
  USING (has_role('super_admin'));

CREATE POLICY "ai_finder_program_matches_delete_super_admin" ON public.ai_finder_program_matches
  FOR DELETE TO authenticated
  USING (has_role('super_admin'));


-- ============================================================
-- TABLE: ai_conversations
-- ============================================================
-- A chat session. May be associated with a specific student
-- profile (e.g. a Finder follow-up) or be a general study-abroad
-- chat. Separate from Finder results.
--
-- Browser-authenticated users may create and manage their own
-- logged-in conversations (user_id set, non-null).
-- If student_profile_id is provided, it must belong to auth.uid()
-- and must be a non-anonymous profile — this is enforced in the
-- INSERT and UPDATE WITH CHECK clauses.
-- Anonymous conversations (user_id NULL) are created exclusively
-- via server endpoints (service role) and must be tied to an
-- anonymous student profile through chk_ai_conversations_owner_context.
-- ------------------------------------------------------------
CREATE TABLE public.ai_conversations (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Null for anonymous conversations. Set for logged-in users.
  user_id             uuid        REFERENCES public.user_profiles(id)   ON DELETE CASCADE,

  -- Optional link to the student profile this chat is based on.
  student_profile_id  uuid        REFERENCES public.student_profiles(id) ON DELETE SET NULL,

  session_type        text        NOT NULL
    CHECK (session_type IN ('finder', 'chat')),

  title               text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  last_message_at     timestamptz,

  -- Set only for anonymous conversations; triggers cleanup cron job.
  expires_at          timestamptz,

  -- Anonymous conversations must be tied to a student profile and must be temporary.
  -- Server endpoints verify anonymous ownership via the linked profile's session_token.
  -- A second session_token column on this table is not added in v1 — ownership is
  -- validated through the student_profile_id → session_token chain.
  CONSTRAINT chk_ai_conversations_owner_context
    CHECK (
      user_id IS NOT NULL
      OR (
        student_profile_id IS NOT NULL
        AND expires_at IS NOT NULL
      )
    )
);

CREATE INDEX idx_ai_conversations_user_id            ON public.ai_conversations (user_id);
CREATE INDEX idx_ai_conversations_student_profile_id ON public.ai_conversations (student_profile_id);
CREATE INDEX idx_ai_conversations_session_type       ON public.ai_conversations (session_type);
CREATE INDEX idx_ai_conversations_created_at         ON public.ai_conversations (created_at);
CREATE INDEX idx_ai_conversations_last_message_at    ON public.ai_conversations (last_message_at);
CREATE INDEX idx_ai_conversations_expires_at         ON public.ai_conversations (expires_at);
-- Used by cleanup cron job.
CREATE INDEX idx_ai_conversations_expires_nonnull    ON public.ai_conversations (expires_at)
  WHERE expires_at IS NOT NULL;

ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;

-- Logged-in users can read their own conversations.
CREATE POLICY "ai_conversations_select_own" ON public.ai_conversations
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- Logged-in users can start conversations linked to their own user_id.
-- WITH CHECK enforces:
--   1. user_id = auth.uid() — prevents null user_id (no anonymous rows via browser).
--   2. If student_profile_id is set, it must be the user's own non-anonymous profile.
--      This prevents a user from linking a conversation to another user's profile
--      by guessing its UUID, or linking to an anonymous profile via the browser.
-- Anonymous conversations are created exclusively via server endpoints (service role).
CREATE POLICY "ai_conversations_insert_own" ON public.ai_conversations
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND (
      student_profile_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.student_profiles sp
        WHERE sp.id      = ai_conversations.student_profile_id
          AND sp.user_id = auth.uid()
          AND sp.is_anonymous = false
      )
    )
  );

-- Logged-in users can update their own conversations (e.g. rename title).
-- Server also updates last_message_at via service role.
-- WITH CHECK enforces the same student_profile_id ownership rules as INSERT,
-- and prevents reassigning user_id or converting the conversation to anonymous.
CREATE POLICY "ai_conversations_update_own" ON public.ai_conversations
  FOR UPDATE TO authenticated
  USING    (user_id = auth.uid())
  WITH CHECK (
    user_id = auth.uid()
    AND (
      student_profile_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.student_profiles sp
        WHERE sp.id      = ai_conversations.student_profile_id
          AND sp.user_id = auth.uid()
          AND sp.is_anonymous = false
      )
    )
  );

-- Logged-in users can delete their own conversations (cascades to ai_messages).
CREATE POLICY "ai_conversations_delete_own" ON public.ai_conversations
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

-- super_admin can read and delete all conversations.
CREATE POLICY "ai_conversations_select_super_admin" ON public.ai_conversations
  FOR SELECT TO authenticated
  USING (has_role('super_admin'));

CREATE POLICY "ai_conversations_delete_super_admin" ON public.ai_conversations
  FOR DELETE TO authenticated
  USING (has_role('super_admin'));


-- ============================================================
-- TABLE: ai_messages
-- ============================================================
-- Individual messages within an AI conversation.
-- Messages are append-only — never updated after creation.
-- context_used stores the DegreeWiki data records that were
-- fetched and injected into the LLM prompt for this turn.
--
-- Write access (INSERT/UPDATE/DELETE) is intentionally server-only.
-- The server endpoint must validate the role field, call the LLM,
-- track cost in ai_usage_logs, and store context_used atomically.
-- Allowing browser INSERT would let clients write arbitrary role
-- values (including 'assistant'/'system') and bypass cost tracking.
-- All message rows are written via service role through server endpoints.
-- ------------------------------------------------------------
CREATE TABLE public.ai_messages (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  ai_conversation_id      uuid        NOT NULL REFERENCES public.ai_conversations(id) ON DELETE CASCADE,

  role                    text        NOT NULL
    CHECK (role IN ('user', 'assistant', 'system')),

  content                 text        NOT NULL,

  -- DegreeWiki records injected into the LLM context for this turn.
  context_used            jsonb,

  ai_model_used           text,
  prompt_token_count      integer     NOT NULL DEFAULT 0,
  completion_token_count  integer     NOT NULL DEFAULT 0,

  created_at              timestamptz NOT NULL DEFAULT now()
  -- No updated_at — messages are never edited after creation.
);

CREATE INDEX idx_ai_messages_conversation_id ON public.ai_messages (ai_conversation_id);
CREATE INDEX idx_ai_messages_role            ON public.ai_messages (role);
CREATE INDEX idx_ai_messages_created_at      ON public.ai_messages (created_at);

ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY;

-- Logged-in users can read messages in their own conversations.
CREATE POLICY "ai_messages_select_own" ON public.ai_messages
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.ai_conversations ac
      WHERE ac.id      = ai_messages.ai_conversation_id
        AND ac.user_id = auth.uid()
    )
  );

-- No INSERT policy for authenticated clients.
-- No UPDATE policy for authenticated clients.
-- No DELETE policy for authenticated clients.
-- All message writes go through server endpoints using the service role.
-- This ensures role validation, LLM cost tracking, and context storage
-- happen atomically server-side before any row is persisted.

-- super_admin can read and delete messages for support and moderation.
CREATE POLICY "ai_messages_select_super_admin" ON public.ai_messages
  FOR SELECT TO authenticated
  USING (has_role('super_admin'));

CREATE POLICY "ai_messages_delete_super_admin" ON public.ai_messages
  FOR DELETE TO authenticated
  USING (has_role('super_admin'));


-- ============================================================
-- TABLE: ai_usage_logs
-- ============================================================
-- Cost and token audit log for every AI call made on behalf of
-- a user or anonymous session.
--
-- Written ONLY by server endpoints using the service role.
-- No authenticated INSERT policy is created — all writes bypass RLS.
-- This table is append-only; no UPDATE or DELETE for browser clients.
-- SELECT is restricted to staff with the view_ai_logs permission.
-- ------------------------------------------------------------
CREATE TABLE public.ai_usage_logs (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Null if the session was anonymous (no linked user account).
  user_id             uuid        REFERENCES public.user_profiles(id) ON DELETE SET NULL,

  session_type        text        NOT NULL
    CHECK (session_type IN ('finder', 'chat')),

  tokens_used         integer     NOT NULL DEFAULT 0,
  model_used          text,
  cost_estimate_usd   numeric,

  created_at          timestamptz NOT NULL DEFAULT now()
  -- No updated_at — rows are never modified after creation.
);

CREATE INDEX idx_ai_usage_logs_user_id      ON public.ai_usage_logs (user_id);
CREATE INDEX idx_ai_usage_logs_session_type ON public.ai_usage_logs (session_type);
CREATE INDEX idx_ai_usage_logs_model_used   ON public.ai_usage_logs (model_used);
CREATE INDEX idx_ai_usage_logs_created_at   ON public.ai_usage_logs (created_at);

ALTER TABLE public.ai_usage_logs ENABLE ROW LEVEL SECURITY;

-- Only staff with view_ai_logs permission or super_admin may read usage logs.
-- No public SELECT. No authenticated student SELECT.
CREATE POLICY "ai_usage_logs_select_permitted" ON public.ai_usage_logs
  FOR SELECT TO authenticated
  USING (
    has_permission('view_ai_logs')
    OR has_role('super_admin')
  );

-- No INSERT policy for authenticated clients.
-- All writes use the service role through server endpoints.

-- No UPDATE or DELETE policies.
-- ai_usage_logs is an immutable audit log.
