-- ============================================================
-- Migration 019: Add 'skipped' to staging import_status checks
-- ============================================================
-- Tables altered:
--   staging_universities
--   staging_programs
--   staging_scholarships
--   staging_articles
--
-- Constraint names (auto-generated by PostgreSQL from inline CHECKs):
--   staging_universities_import_status_check
--   staging_programs_import_status_check
--   staging_scholarships_import_status_check
--   staging_articles_import_status_check
--
-- If a DROP CONSTRAINT fails, verify names with:
--   SELECT constraint_name FROM information_schema.table_constraints
--   WHERE table_name IN (
--     'staging_universities', 'staging_programs',
--     'staging_scholarships', 'staging_articles'
--   ) AND constraint_type = 'CHECK';
--
-- Final allowed import_status values on all four tables:
--   pending, processing, validated, duplicate_detected,
--   needs_review, approved, rejected, error, skipped
--
-- Depends on:
--   010_import_staging     — staging_universities, staging_programs, staging_scholarships
--   018_import_staging_articles — staging_articles
-- ============================================================


-- ============================================================
-- 1. staging_universities
-- ============================================================
ALTER TABLE public.staging_universities
  DROP CONSTRAINT staging_universities_import_status_check,
  ADD CONSTRAINT staging_universities_import_status_check
    CHECK (import_status IN (
      'pending', 'processing', 'validated', 'duplicate_detected',
      'needs_review', 'approved', 'rejected', 'error', 'skipped'
    ));


-- ============================================================
-- 2. staging_programs
-- ============================================================
ALTER TABLE public.staging_programs
  DROP CONSTRAINT staging_programs_import_status_check,
  ADD CONSTRAINT staging_programs_import_status_check
    CHECK (import_status IN (
      'pending', 'processing', 'validated', 'duplicate_detected',
      'needs_review', 'approved', 'rejected', 'error', 'skipped'
    ));


-- ============================================================
-- 3. staging_scholarships
-- ============================================================
ALTER TABLE public.staging_scholarships
  DROP CONSTRAINT staging_scholarships_import_status_check,
  ADD CONSTRAINT staging_scholarships_import_status_check
    CHECK (import_status IN (
      'pending', 'processing', 'validated', 'duplicate_detected',
      'needs_review', 'approved', 'rejected', 'error', 'skipped'
    ));


-- ============================================================
-- 4. staging_articles
-- ============================================================
ALTER TABLE public.staging_articles
  DROP CONSTRAINT staging_articles_import_status_check,
  ADD CONSTRAINT staging_articles_import_status_check
    CHECK (import_status IN (
      'pending', 'processing', 'validated', 'duplicate_detected',
      'needs_review', 'approved', 'rejected', 'error', 'skipped'
    ));
